import { cn } from "@/lib/utils";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(" min-h-screen font-sans antialiased")}>
        {children}
      </body>
    </html>
  );
}
